volumes:
  keycloak_aio_postgres_data:
    driver: local

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
  
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: 'always'
    volumes:
      - keycloak_aio_postgres_data:/var/lib/postgresql/data
  
  keycloak-1:
    hostname: keycloak-1
    container_name: keycloak-1
    image: quay.io/keycloak/keycloak:23.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_HOST: postgres
      KC_DB_PORT: 5432
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME_STRICT: false         #deactivate fixed hostname
      KC_HOSTNAME_STRICT_HTTPS: false   #for local access to console admin in start mode
      KC_HTTP_ENABLED: true
    command:
      - start
      - --cache-stack=tcp
    depends_on:
      - postgres

  keycloak-2:
    hostname: keycloak-2
    container_name: keycloak-2
    image: quay.io/keycloak/keycloak:23.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_HOST: postgres
      KC_DB_PORT: 5432
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME_STRICT: false         #deactivate fixed hostname
      KC_HOSTNAME_STRICT_HTTPS: false   #for local access to console admin in start mode
      KC_HTTP_ENABLED: true
    command:
      - start
      - --cache-stack=tcp
    depends_on:
      - postgres